Fixed length of root field in tx receipt response
rsksmart/rskj pull request #1339
Opened 2020-10-20 16:21 UTC by Vovchyk

This sets the length of the `root` field that's being returned by `eth_getTransactionReceipt` JSON-RPC call to 32 bytes.

## Description
Right now rskj returns 0x00,0x01 instead of 0x0...0 and 0x0...1 (32 bytes) for the `root` field. This makes some js libraries incompatible with rskj.

## Motivation and Context
This change is required for the rskj node to be compatible with client libraries at the JSON-RPC level.

## How Has This Been Tested?
JSON-RPC response of `eth_getTransactionReceipt` has been checked.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2020-10-22 20:10 UTC, patogallaiovlabs requested changes
We could add a test for the final DTO, that we currently dont have

2020-10-22 20:10 UTC, patogallaiovlabs commented on rskj-core/src/test/java/org/ethereum/util/ByteUtilTest.java
> +        }
I would add an assert of the last byte, matching the src.

2020-10-23 18:48 UTC, fedejinich commented
is it posible to add a test case for `testToBytesWithLeadingZeros_TxReceiptRoot`?

2020-10-26 17:52 UTC, patogallaiovlabs approved these changes

2020-11-09 14:39 UTC, patogallaiovlabs approved these changes

2020-11-09 15:39 UTC, ajlopezrsk approved these changes

2020-11-09 15:39 UTC, merged