Create FastBridgeCompatibleBtcWallet class in order to support fast BTC feature
rsksmart/rskj pull request #1344
Opened 2020-10-23 19:48 UTC by guidohernan93

- Refactor RegisterBtcWallet class
- Refactor BridgeUtils methods involving spendWallet and noSpendWallet as boolean parameter is added to check if wallet is compatible with fast bridge
- Refactored all the tests that made use of these methods and add test for FastBridgeCompatibleBtcWallet class

2020-10-26 14:33 UTC, josedahlquist requested changes

2020-10-26 14:33 UTC, josedahlquist commented on rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java
> +            Optional<Federation> destinationFederation = getDestinationFederation(payToScriptHash);
You should be using the `fastBridgeFederationInformation` payToScriptHash.
The way you are trying to get the destination address won't work

2020-10-26 21:13 UTC, josedahlquist commented on rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java
> +                fastBridgeFederationInformation.get().getFederationScriptHash());
```suggestion
            FastBridgeFederationInformation fastBridgeFederationInformationInstance = fastBridgeFederationInformation.get(); 
            Optional<Federation> destinationFederation = getDestinationFederation(
                fastBridgeFederationInformationInstance.getFederationScriptHash()
            );
```
Seems like you are "getting" the optional many times, maybe get it just once into a variable

2020-10-26 21:13 UTC, josedahlquist commented on rskj-core/src/test/java/co/rsk/peg/FastBridgeCompatibleBtcWalletTest.java
> +        );
```suggestion
        when(provider.getFastBridgeFederationInformation(fastBridgeFederationP2SH))
           .thenReturn(Optional.of(fastBridgeFederationInformation));
```

2020-10-27 15:05 UTC, josedahlquist approved these changes

2020-10-27 15:22 UTC, pamgonzalez commented on rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
> +        return getFederationsSpendWallet(btcContext, Collections.singletonList(federation), utxos,
please, try to maintain the code standards.

2020-10-27 15:22 UTC, pamgonzalez commented on rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
> +        List<UTXO> utxos, boolean isFastBridgeCompatible, BridgeStorageProvider storageProvider) {
please, try to maintain the code standards.

2020-10-27 15:22 UTC, pamgonzalez commented on rskj-core/src/main/java/co/rsk/peg/FastBridgeCompatibleBtcWallet.java
> +    public FastBridgeCompatibleBtcWallet(Context btcContext, List<Federation> federations,
please, try to maintain the code standards.

2020-10-27 17:48 UTC, josedahlquist approved these changes

2020-10-27 17:50 UTC, pamgonzalez approved these changes

2020-10-27 17:50 UTC, merged