Consider MGP in eth_getPrice
rsksmart/rskj pull request #1377
Opened 2020-11-26 12:33 UTC by Vovchyk

Considering best block's MGP in `eth_getPrice`.

## Description
This change takes into account best block's MGP while calculating gas price in the `eth_getPrice` JSON-RPC method. This resolves #1343

## Motivation and Context

## How Has This Been Tested?

Using unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2020-11-26 18:50 UTC, donequis commented on rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
> +    private void onTransaction(Transaction tx) {
Empty blocks or unusued block space should reduce the suggested gas price, which is not happening with this formula. Probably an idea to track in the backlog, nothing actually related to this task

2020-11-27 19:57 UTC, patogallaiovlabs requested changes

2020-11-27 19:57 UTC, patogallaiovlabs commented on rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
> +    private static Coin max(Coin a, Coin b) {
wouldnt be better to declare max() in Coin? would be consistent with BigInteger.max()

2020-11-30 13:42 UTC, patogallaiovlabs commented on rskj-core/src/main/java/org/ethereum/listener/GasPriceTracker.java
> +    private static Coin max(Coin a, Coin b) {
nice :)

2020-11-30 13:43 UTC, patogallaiovlabs submitted a review, later dismissed
LGTM

2020-12-14 16:18 UTC, jjtechuy commented
pipeline: run

2020-12-17 16:43 UTC, ajlopezrsk approved these changes

2020-12-17 16:43 UTC, merged