Fast bridge burning utxos fix
rsksmart/rskj pull request #1498
Opened 2021-04-09 20:35 UTC by marcos-iov

When a fast bridge Federation UTXO is spent, it probably generates a change UTXO, this change UTXO is then registered via registerBtcTransaction, but the logic in this method detects the transaction as an attempted peg-in, which will be rejected because the FB Federation is a multisig. This will burn the funds because the FB Federation won't register those funds.

Fix:
Extract the standard redeem script from the input using the existing bitcoinj logic, and compare it against the active federations redeem script. If it matches, then don't process the tx as a peg-in

2021-04-12 14:58 UTC, josedahlquist approved these changes

2021-04-12 16:12 UTC, pamgonzalez commented on rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
> +    public void testIsPegInTx_hasChangeUtxoFromFastBridgeFederation() {
Could you include the expected result in the tittle?

2021-04-12 16:12 UTC, pamgonzalez commented on rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
> +    public void testIsPegInTx_hasChangeUtxoFromFastBridgeErpFederation() {
Could you include the expected result in the tittle?

2021-04-12 16:12 UTC, pamgonzalez commented on rskj-core/src/test/java/co/rsk/peg/BridgeUtilsTest.java
> +    public void testIsPegInTx_hasChangeUtxoFromErpFederation() {
Could you include the expected result in the tittle?

2021-04-15 15:27 UTC, donequis commented on rskj-core/src/main/java/co/rsk/peg/BridgeUtils.java
> +            RedeemScriptParser redeemScriptParser = RedeemScriptParserFactory.get(tx.getInput(index).getScriptSig().getChunks());
I don't immediatelly see exploit here, but I see issues.

On one side, the `RedeemScriptParserFactory.get` could match an ERP style formed by non real erp members. Meaning that someone can create an ERP style redeem script with valid format, valid federators, but wrong ERP memebers, and here it would match. This can be possible be used to create a fork between updated and non updated nodes pre activation.

I would add some activation guard here and think carefully if we want the redeemscriptparserfactory to know the erp federation and the timelock parameter

2021-04-20 16:57 UTC, marcos-iov commented
pipeline:run

2021-04-21 03:20 UTC, donequis approved these changes

2021-04-21 03:21 UTC, donequis requested changes
Don't know how to cancel approbal

2021-04-21 03:24 UTC, donequis requested changes
When checking if the transaction is a pegout or a migration transaction we should check the same we do on pegin for fast bridge transactions.

2021-04-21 03:26 UTC, donequis commented
I mean, `isMigrationTx` and `isPegOutTx` should also match fast bridge transactions in a nicer way

2021-04-26 12:56 UTC, pamgonzalez submitted a review, later dismissed

2021-04-26 15:15 UTC, donequis approved these changes

2021-04-26 15:21 UTC, josedahlquist commented
pipeline:run

2021-04-26 17:27 UTC, marcos-iov commented
pipeline:run

2021-04-26 18:58 UTC, josedahlquist approved these changes

2021-04-26 19:06 UTC, merged