Support blockHash filter in eth_getLogs JSON-RPC method
rsksmart/rskj pull request #1527
Opened 2021-05-10 20:46 UTC by marcciosilva

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2021-05-10 20:47 UTC, marcciosilva commented on rskj-core/src/main/java/co/rsk/rpc/modules/eth/subscribe/EthSubscribeLogsParams.java
> +    // TODO: modify?
@fedejinich should I modify this class as well?
I assume clients can subscribe to events and receive logs somehow, and this is what it's for (or maybe it's deprecated, I really can't tell).

2021-05-11 20:00 UTC, fedejinich requested changes

2021-05-11 20:00 UTC, fedejinich commented on rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
> +    public void getLogsFromBlockchainWithEventInContractCreationReturnsAsExpectedWithBlockHashFilter() throws Exception {
nice!

2021-05-11 20:00 UTC, fedejinich commented on rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
should we also cover an unexisting block hash case?

2021-05-12 14:26 UTC, marcciosilva commented
pipeline: run

2021-05-12 16:27 UTC, fedejinich commented on rskj-core/src/test/java/org/ethereum/rpc/Web3ImplLogsTest.java
:D

2021-05-12 16:29 UTC, fedejinich submitted a review, later dismissed
lgtm!

2021-05-12 16:29 UTC, fedejinich commented
pipeline:run

2021-05-12 17:26 UTC, marcciosilva commented
pipeline: run

2021-05-12 17:30 UTC, marcciosilva commented
pipeline: run

2021-05-12 17:38 UTC, fedejinich commented
pipeline:run

2021-06-10 14:15 UTC, fedejinich approved these changes
lgtm!

2021-06-10 15:29 UTC, merged