Enabled Fast Block Propagation by default
rsksmart/rskj pull request #1677
Opened 2021-12-20 11:59 UTC by rmoreliovlabs

We wan to enable fast block proagation by default

## Description
Updated all `.conf` to enable this feature by default.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2022-01-05 12:47 UTC, Vovchyk requested changes

2022-01-05 12:47 UTC, Vovchyk commented on rskj-core/src/main/resources/reference.conf
> +    fastBlockPropagation = true
it looks like there's no need to enable the feature in every config file. Doing this in `reference.conf` should be enough

2022-01-07 13:17 UTC, rmoreliovlabs commented
pipeline:run

2022-01-10 09:21 UTC, Vovchyk submitted a review, later dismissed

2022-01-25 15:33 UTC, Vovchyk approved these changes

2022-01-25 16:26 UTC, Vovchyk commented
pipeline:run

2022-01-25 16:27 UTC, Vovchyk commented
pipeline:run

2022-01-25 16:45 UTC, Vovchyk commented
pipeline:run

2022-01-25 16:45 UTC, Vovchyk commented
pipeline:run

2022-01-25 18:00 UTC, rmoreliovlabs commented
pipeline:run

2022-01-26 07:52 UTC, Vovchyk commented
pipeline:run

2022-01-26 07:52 UTC, Vovchyk commented
pipeline:run

2022-01-26 08:11 UTC, merged