Accept websocket connection without '/websocket'
rsksmart/rskj pull request #1753
Opened 2022-04-12 22:33 UTC by rmoreliovlabs

## Description
This change allows `WebSocketServerProtocolHandler` to accept any url path. Basically ignores everything after `host:server`.

## Motivation and Context
Alejandro Cavallero reported that there are users reporting that is tricky and a problem to require ‘/websocket’ in the endpoint. Is it possible to accept both ws://your-ip:4445 and ws://your-ip:4445/websocket

## How Has This Been Tested?
We added a unit test and also we did some manual testing using Postman websockets feature.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2022-04-15 11:30 UTC, Vovchyk requested changes

2022-04-15 11:30 UTC, Vovchyk commented on rskj-core/src/main/java/co/rsk/rpc/netty/Web3WebSocketServer.java
> +                    p.addLast(new RskWebSocketServerProtocolHandler("/", maxFrameSize));
I understand this allows any path, doesn't it? Shouldn't we restrict it to only accept `ws://your-ip:4445/websocket` and `ws://your-ip:4445`?

2022-04-21 12:09 UTC, Vovchyk commented on rskj-core/src/main/java/co/rsk/rpc/netty/Web3WebSocketServer.java
> +                    p.addLast(new RskWebSocketServerProtocolHandler("/", maxFrameSize));
I see. Any way, looks like we support any path for http endpoint too.

Btw.. please check the failed pipeline

2022-04-21 12:09 UTC, Vovchyk approved these changes

2022-04-22 13:29 UTC, rmoreliovlabs commented
pipeline:run

2022-06-09 08:51 UTC, Vovchyk commented
pipeline:run

2022-06-09 09:08 UTC, Vovchyk commented
pipeline:run

2022-06-09 13:23 UTC, Vovchyk commented
pipeline:run

2022-06-14 08:40 UTC, Vovchyk commented
pipeline:run

2022-06-14 09:48 UTC, Vovchyk commented
pipeline:run

2022-06-14 09:48 UTC, Vovchyk commented
pipeline:run

2022-06-14 12:53 UTC, Vovchyk commented
pipeline:run

2022-06-14 13:29 UTC, Vovchyk commented
pipeline:run

2022-06-14 13:57 UTC, Vovchyk approved these changes

2022-06-14 13:57 UTC, merged