Research/parallel-tx/main
rsksmart/rskj pull request #1793
Opened 2022-06-02 18:15 UTC by julianlen

2022-06-27 22:00 UTC, ilanolkies requested changes

2022-06-27 22:00 UTC, ilanolkies commented on rskj-core/src/main/java/co/rsk/core/bc/ParallelizeTransactionHandler.java
> +    public ParallelizeTransactionHandler(short sublists, long sublistGasLimit) {
`sublists` has the same name as `this.sublists`

```suggestion
    public ParallelizeTransactionHandler(short parallelSublistsAmount, long sublistGasLimit) {
```

2022-12-07 10:01 UTC, Vovchyk commented
pipeline:run

2022-12-07 10:02 UTC, Vovchyk commented
pipeline:run

2022-12-14 18:46 UTC, ilanolkies commented
Closing in favor of #1930

2023-05-18 19:38 UTC, closed without merging