Refactor KeyValueDataSource interface
rsksmart/rskj pull request #1858
Opened 2022-08-07 20:41 UTC by SergioDemianLerner

Removal of execution code from the KeyValueDataSource interface, and move it to KeyValueDataSourceUtils. 
The refactor revealed a potential source of confusion where the key KEYVALUE_DATASOURCE_PROP_NAME was used for two unrelated things (database type determination and node configuration). 
Now there are two different keys: 
* PROPERTY_KEYVALUE_DATASOURCE  (for configuration)
* KEYVALUE_DATASOURCE_PROP_NAME (for database type determination)

## Description
We take out of the KeyValueDataSource interface the functionality to create a database  (LevelDB or RocksDB).

## Motivation and Context

- An interface should not contain execution code
- An abstract interface should not reference concrete implementations of that interface (LevelDB / RocksDB) because that defeats its abstraction purpose
- An identifier (KEYVALUE_DATASOURCE_PROP_NAME) should not be used for two unrelated things
- The KEYVALUE_DATASOURCE_PROP_NAME identifier should be private and not public, to enable changing the database type determination in the future.

## How Has This Been Tested?

All tests pass. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

2022-08-15 15:30 UTC, Vovchyk requested changes
@SergioDemianLerner , thanks for the effort.

Could you please address Sonar complaints?

2022-08-15 15:30 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSourceUtils.java
> +    static private String DB_KIND_PROPERTIES_FILE = "dbKind.properties";
```suggestion
    private static final String DB_KIND_PROPERTIES_FILE = "dbKind.properties";
```

2022-08-15 15:30 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/datasource/KeyValueDataSourceUtils.java
> +    static private String KEYVALUE_DATASOURCE_PROP_NAME = "keyvalue.datasource";
```suggestion
    private static final String KEYVALUE_DATASOURCE_PROP_NAME = "keyvalue.datasource";
```

2022-09-15 09:22 UTC, illuque-iov approved these changes

2023-03-02 14:31 UTC, Vovchyk commented
pipeline:run

2023-03-02 17:02 UTC, Vovchyk commented
pipeline:run

2023-03-03 09:27 UTC, Vovchyk commented
pipeline:run

2023-03-06 12:37 UTC, Vovchyk commented
pipeline:run

2023-03-07 09:24 UTC, Vovchyk commented
pipeline:run

2023-05-18 08:52 UTC, Vovchyk commented
pipeline:run

2023-05-18 10:27 UTC, Vovchyk approved these changes

2023-05-18 10:28 UTC, merged