Junit5 update
rsksmart/rskj pull request #1878
Opened 2022-09-12 19:18 UTC by illuque-iov

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2022-09-13 07:17 UTC, illuque-iov commented
pipeline:run

2022-09-13 10:33 UTC, illuque-iov commented
pipeline:run

2022-09-13 13:30 UTC, rmoreliovlabs approved these changes

2022-10-03 10:42 UTC, Vovchyk requested changes

2022-10-03 11:04 UTC, illuque-iov commented on rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class, () -> factory.decodeHeader(encodedHeader));
Because `factory.decodeHeader` is what throws the exception, those two checks were never performed on previous version.

2022-10-03 11:07 UTC, illuque-iov commented on rskj-core/src/test/java/co/rsk/crypto/EncryptedDataTest.java
> +        Assertions.assertEquals(ed, ed2);
Redundant, no? Comparing same object

2022-10-03 11:15 UTC, Vovchyk commented on rskj-core/src/test/java/co/rsk/crypto/EncryptedDataTest.java
> +        Assertions.assertEquals(ed, ed2);
it seemed to me that `equals()` is being tested by that

2022-10-03 11:24 UTC, illuque-iov commented on rskj-core/src/test/java/co/rsk/mine/MinerServerOrchidTest.java
> +        setUp(NetworkUpgrades.BAMBOO_PROPERTIES.getProperties());
Oh, good catch, copy/paster error 🤦

2022-10-03 11:24 UTC, illuque-iov commented on rskj-core/src/test/java/org/ethereum/validator/ProofOfWorkRuleOrchidTest.java
> +        setUp(NetworkUpgrades.BAMBOO_PROPERTIES.getProperties());
Oh, good catch, copy/paster error 🤦

2022-10-13 07:57 UTC, illuque-iov commented on rskj-core/src/test/java/co/rsk/core/BlockFactoryTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class, () -> factory.decodeHeader(encodedHeader));
https://github.com/rsksmart/rskj/pull/1878#discussion_r985656962

2022-10-13 12:53 UTC, Vovchyk submitted a review, later dismissed

2022-10-13 13:00 UTC, illuque-iov commented
pipeline:run

2022-10-21 15:32 UTC, illuque-iov commented
pipeline:run

2022-10-21 15:54 UTC, illuque-iov commented
pipeline:run

2022-10-21 16:34 UTC, illuque-iov commented
pipeline:run

2022-10-24 07:59 UTC, illuque-iov commented
pipeline:run

2022-10-24 08:28 UTC, Vovchyk approved these changes

2022-10-24 08:46 UTC, merged