Set methods in BridgeEventLogger as default
rsksmart/rskj pull request #1890
Opened 2022-09-27 04:00 UTC by jeremy-then

2022-09-30 12:39 UTC, marcos-iov submitted a review, later dismissed
Well done!

2022-09-30 19:06 UTC, kelvinator07 approved these changes

2022-10-06 13:33 UTC, rmoreliovlabs requested changes
Could you write some description and context about what and why we are adding these changes?

2022-10-06 16:47 UTC, marcos-iov approved these changes

2022-10-06 16:48 UTC, merged