Add script to update gradle deps related files
rsksmart/rskj pull request #1908
Opened 2022-10-20 19:21 UTC by rmoreliovlabs

## Description
Added script in order to update project dependencies

## Motivation and Context
In the project we keep a file with hashes of all dependencies we reference in the gradle file - ./gradle/verification-metadata.xml.

If new deps are added or existing ones are updated, we need to re-generate this XML file using this command:

`./gradlew --no-daemon --refresh-dependencies --write-verification-metadata sha256 assemble`

More info [here](https://docs.gradle.org/6.5/userguide/dependency_verification.html#sec:troubleshooting-verificaton).

As an improvement, we may have a shell script in the project, which would simplify this process. That script can run that long gradle command to re-generate the verification-metadata.xml file.

The script could simplify life of external contributors, as well as internal devs

Also we may update our wiki to mention about this capability.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2022-10-21 10:38 UTC, Vovchyk requested changes
`update-deps.sh`? also I'd put it into the `scripts` folder, what do you think?

seems this command adds new entries of new dependencies to the metadata file, but also preserves older ones. Do you know if this command has an option to remove older / obsolete entries from the xml file?

2022-10-24 17:29 UTC, rmoreliovlabs commented
>

2022-10-24 17:30 UTC, rmoreliovlabs commented
> `update-deps.sh`? also I'd put it into the `scripts` folder, what do you think?
> 
> seems this command adds new entries of new dependencies to the metadata file, but also preserves older ones. Do you know if this command has an option to remove older / obsolete entries from the xml file?

Addressed comment but also found this: https://docs.gradle.org/current/userguide/dependency_verification.html#sec:verification-metadata-hygiene.

Let me know what you think about it

2022-10-26 08:00 UTC, Vovchyk requested changes
I'd also add the `.sh` extension to the script name to make it easily identifiable as a shell script

2022-10-26 08:00 UTC, Vovchyk commented on scripts/update-verification-metadata
> +cd ../
```suggestion

```

script is supposed to be executed in the project's root directory, so no need to `cd`

2022-10-26 08:00 UTC, Vovchyk commented on scripts/update-verification-metadata
> +./gradlew --no-daemon --refresh-dependencies --write-verification-metadata sha256 assemble
```suggestion
set -e

# remove the verification-metadata.xml file with old deps (if any), and replace it with the template
if [ -f ./gradle/verification-metadata.xml ]; then
  rm ./gradle/verification-metadata.xml
  cp ./scripts/verification-metadata-template.xml ./gradle/verification-metadata.xml
fi

# generate verification-metadata.xml
./gradlew --no-daemon --refresh-dependencies --write-verification-metadata sha256 assemble
```

better to fail ( via `set -e` ) and exit, if for some reason file cannot be removed or the template is missing

2022-10-26 15:06 UTC, Vovchyk commented
@rmoreliovlabs , I see you marked it as resolved. What are your thoughts on this?

> I'd also add the .sh extension to the script name to make it easily identifiable as a shell script

Also please make sure the pipeline is green

2022-10-27 13:26 UTC, rmoreliovlabs commented
> @rmoreliovlabs , I see you marked it as resolved. What are your thoughts on this?
> 
> > I'd also add the .sh extension to the script name to make it easily identifiable as a shell script
> 
> Also please make sure the pipeline is green

Sorry I forgot to push the changes

2022-10-27 13:46 UTC, Vovchyk approved these changes

2022-10-27 18:22 UTC, rmoreliovlabs commented
pipeline:run

2022-10-27 18:42 UTC, rmoreliovlabs commented
pipeline:run

2022-10-28 09:41 UTC, Vovchyk commented
pipeline:run

2022-10-31 08:53 UTC, Vovchyk commented
pipeline:run

2022-10-31 10:13 UTC, Vovchyk commented
pipeline:run

2022-10-31 11:15 UTC, Vovchyk approved these changes

2023-02-27 13:42 UTC, merged