Updating ethereum_summitTransaction method and personal_sendTransaction
rsksmart/rskj pull request #1917
Opened 2022-11-08 09:19 UTC by asoto-iov

Updated `Ethereum#summitTransaction` method to return the result of adding the transaction to the pool so the caller can check if it was successful or not.
Updated the JRPC method `personal_sendTransaction` to behave the same as `eth_sendTransaction` when the transaction can not be added to the pool.

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2022-11-08 16:59 UTC, asoto-iov commented
fed:update_simple_ethereum_implementation

2022-11-08 17:01 UTC, asoto-iov commented
pipeline:run

2022-11-08 17:21 UTC, asoto-iov commented
pipeline:run

2022-11-08 18:44 UTC, illuque-iov commented
pipeline:run

2022-11-09 17:00 UTC, illuque-iov commented on rskj-core/src/test/java/co/rsk/rpc/modules/personal/PersonalModuleTest.java
> +        when(transactionPoolAddResult.transactionsWereAdded()).thenReturn(true);
duplicated?

2022-11-11 12:39 UTC, Vovchyk requested changes

2022-11-11 12:39 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/facade/Ethereum.java
> +     *                    return the result of adding the transaction to the pool.
```suggestion
     * @return the result of adding the transaction to the pool.
```

2022-11-11 12:40 UTC, Vovchyk commented
please make sure the pipeline has passed. It may need a rebase for that

2022-11-15 10:02 UTC, asoto-iov commented
pipeline:run

2022-11-17 00:03 UTC, marcos-iov submitted a review, later dismissed

2022-11-24 15:01 UTC, Vovchyk approved these changes

2023-01-17 09:54 UTC, Vovchyk commented
pipeline:run

2023-01-17 11:11 UTC, Vovchyk commented
pipeline:run

2023-01-17 11:19 UTC, Vovchyk approved these changes

2023-01-17 12:07 UTC, Vovchyk commented
pipeline:run

2023-01-17 12:36 UTC, Vovchyk commented
pipeline:run

2023-01-17 13:29 UTC, Vovchyk commented
pipeline:run

2023-01-17 15:09 UTC, merged