Prevent movedRemainingGasToChild flag from being reverted to false on contracts with multiple CALL op codes
rsksmart/rskj pull request #1992
Opened 2023-03-10 12:10 UTC by illuque-iov

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2023-05-12 17:31 UTC, illuque-iov commented
pipeline:run

2023-05-12 17:53 UTC, illuque-iov commented
pipeline:run

2023-05-15 07:52 UTC, Vovchyk requested changes

2023-05-15 08:07 UTC, illuque-iov commented on rskj-core/src/main/java/org/ethereum/vm/program/ProgramResult.java
> +        if (this.movedRemainingGasToChild) {
Yes, much better. I thought I was going to use to for testing but then I didn't. Will change it.

2023-05-15 08:12 UTC, illuque-iov commented on rskj-core/src/main/java/co/rsk/rpc/modules/eth/EthModule.java
> +        estimatedGas = Math.min(estimatedGas, gasEstimationCap);
Yes, as I understand it, that or some bug maybe. Will log it.

2023-05-15 08:49 UTC, Vovchyk approved these changes

2023-05-26 16:16 UTC, asoto-iov approved these changes

2023-06-27 11:30 UTC, Vovchyk commented
pipeline:run

2023-06-27 13:00 UTC, merged