Draft EIP-2028: calldata gas cost reduction
rsksmart/rskj pull request #2030
Opened 2023-05-03 21:00 UTC by patogallaiovlabs

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2023-06-01 16:53 UTC, rmoreliovlabs requested changes

2023-06-01 16:53 UTC, rmoreliovlabs commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        return (this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION) + zeroVals * GasCost.TX_ZERO_DATA + nonZeroes * getTxNoZeroData(activations);
Can we make this more readable?

A suggestions can be:
```
long transactionCost =  this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION;

long transactionZeroData = getTxNoZeroData(activations);

long totalTransactionCost = transactionCost + zeroVals * GasCost.TX_ZERO_DATA + nonZeroes * transactionZeroData;

return totalTransactionCost;
```

I think this just to make it easier to read the calculation process.

2023-06-02 19:41 UTC, rmoreliovlabs requested changes
Also some tests are failing due to a bad mock for `config.getActivationConfig()` I think you should keep the feature disabled and only activate it for the new tests you will add so you can assert the new calculated values.

2023-06-15 03:48 UTC, rmoreliovlabs commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        return (this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION) + zeroVals * GasCost.TX_ZERO_DATA + nonZeroes * getTxNoZeroData(activations);
Done

2023-06-15 14:50 UTC, Vovchyk requested changes

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        long transactionCost =  this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION;
```suggestion
        long transactionCost = this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION;
```

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        return activations.isActive(ConsensusRule.RSKIPXXX)? GasCost.TX_NO_ZERO_DATA_EIP2028 : GasCost.TX_NO_ZERO_DATA;
```suggestion
        return activations.isActive(ConsensusRule.RSKIPXXX) ? GasCost.TX_NO_ZERO_DATA_EIP2028 : GasCost.TX_NO_ZERO_DATA;
```

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +    private static long getTxNoZeroData(ActivationConfig.ForBlock activations) {
```suggestion
    private static long getTxNonZeroDataCost(ActivationConfig.ForBlock activations) {
```

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        long transactionZeroData = getTxNoZeroData(activations);
```suggestion
        long txNonZeroDataCost = getTxNonZeroDataCost(activations);
```

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/devnet.conf
> +        tbd600 = -1
```suggestion
        tbd600 = 0
```
for devnet and regtest it should be `0`

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/devnet.conf
> +        xxx = -1
not needed

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/main.conf
> +        xxx = -1
not needed

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/regtest.conf
> +        tbd600 = -1
```suggestion
        tbd600 = 0
```
should be 0 for regtest

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/regtest.conf
> +        xxx = -1
not needed

2023-06-15 14:50 UTC, Vovchyk commented on rskj-core/src/main/resources/config/testnet.conf
> +        xxx = -1
not needed

2023-06-15 15:10 UTC, rmoreliovlabs commented on rskj-core/src/main/resources/config/testnet.conf
> +        xxx = -1
Removed

2023-06-15 15:10 UTC, rmoreliovlabs commented on rskj-core/src/main/resources/config/regtest.conf
> +        xxx = -1
Removed

2023-06-15 15:11 UTC, rmoreliovlabs commented on rskj-core/src/main/resources/config/main.conf
> +        xxx = -1
Removed

2023-06-15 15:11 UTC, rmoreliovlabs commented on rskj-core/src/main/resources/config/devnet.conf
> +        xxx = -1
Removed

2023-06-15 15:18 UTC, rmoreliovlabs commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +    private static long getTxNoZeroData(ActivationConfig.ForBlock activations) {
Done

2023-06-15 15:19 UTC, rmoreliovlabs commented on rskj-core/src/main/java/org/ethereum/core/Transaction.java
> +        long transactionCost =  this.isContractCreation() ? GasCost.TRANSACTION_CREATE_CONTRACT : GasCost.TRANSACTION;
Done

2023-06-15 16:09 UTC, Vovchyk reviewed
lgtm!

2023-06-28 20:16 UTC, asoto-iov submitted a review, later dismissed

2023-09-26 15:34 UTC, Vovchyk approved these changes

2023-09-26 16:28 UTC, rmoreliovlabs approved these changes
LGTM

2023-09-27 07:08 UTC, merged