Add trace methods benchmarks
rsksmart/rskj pull request #2036
Opened 2023-05-10 19:20 UTC by rmoreliovlabs

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2023-05-16 17:14 UTC, rmoreliovlabs commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java
> +        this.traceModuleWeb3j = new RskTraceModuleWeb3j(new HttpService(host));
Done

2023-05-16 17:16 UTC, rmoreliovlabs commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskTraceModuleWeb3j.java
> +        private Integer after;
Done

2023-05-16 17:17 UTC, rmoreliovlabs commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskTraceModuleWeb3j.java
> +        private Integer count = 10_000;
Done

2023-05-16 17:18 UTC, rmoreliovlabs commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/RskTraceModuleWeb3j.java
> +        public void setFromBlock(String fromBlock) {
Done

2023-05-16 17:44 UTC, rmoreliovlabs commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/e2e/Web3ConnectorE2E.java
> +    private RskWeb3j.GenericJsonResponse sendRequest(Supplier<Request<?, RskWeb3j.GenericJsonResponse>> supplier) throws HttpRpcException {
Done

2023-05-18 14:19 UTC, Vovchyk requested changes

2023-05-18 14:19 UTC, Vovchyk commented on rskj-core/src/jmh/resources/conf/regtest.conf
> +############################
@rmoreliovlabs , seems this is still not covered, isn't it?

2023-05-19 14:55 UTC, rmoreliovlabs commented on rskj-core/src/jmh/resources/conf/regtest.conf
> +############################
Addressed

2023-05-26 16:19 UTC, asoto-iov commented on rskj-core/src/jmh/java/co/rsk/jmh/web3/plan/GetLogsPlan.java
> +        String blockHash = configuration.getString("getLogs.blockHash");
I would extract this logic to setup stage

2023-05-26 16:19 UTC, asoto-iov approved these changes

2023-06-01 11:17 UTC, merged