Adding some classes to help with Integration Tests
rsksmart/rskj pull request #2337
Opened 2024-05-17 13:17 UTC by fmacleal

- Some refactors made on the Integration Tests classes
- Some classes to easily spin up an rskj node on the integration test, with possibility to check the output from it

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

2024-05-21 12:39 UTC, rmoreliovlabs submitted a review, later dismissed
LGTM

2024-05-24 12:07 UTC, Vovchyk requested changes

2024-05-24 12:07 UTC, Vovchyk commented on rskj-core/src/integrationTest/README.md
> +and validate key features from the tool. We takes sometime to be executed and are part of the CI pipeline to ensure the
```suggestion
and validate key features from the tool. It takes sometime to be executed and is part of the CI pipeline to ensure the
```

2024-05-24 12:07 UTC, Vovchyk commented on rskj-core/src/integrationTest/README.md
> +./gradlew --no-daemon --stacktrace integrationTest
```suggestion
./gradlew --stacktrace integrationTest
```
with daemon next executions might run faster. Is there any specific reason for using this flag?

2024-05-24 13:30 UTC, fmacleal commented
pipeline: run

2024-05-24 13:30 UTC, Vovchyk commented
pipeline:run

2024-05-24 14:23 UTC, Vovchyk approved these changes

2024-05-27 08:10 UTC, merged